---
- hosts: localhost
  become: yes
  become_user: ansible
  become_method: sudo

  roles:
    - Local-preparation

- hosts: GitLab-server
  become: yes
  become_method: sudo

  roles:
    - gitlab-server

- hosts: localhost
  become: yes
  become_user: ansible
  become_method: sudo

  roles:
    - Local-cleaning

