---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Check if GitLab configuration file already exists.
  stat: path=/etc/gitlab/gitlab.rb
  register: gitlab_config_file

- name: Check if GitLab is already installed.
  stat: path=/usr/bin/gitlab-ctl
  register: gitlab_file

# Install GitLab and its dependencies.

- name: Install Epel repository.
  yum: name=epel-release state=present

- name: Install GitLab dependencies.
  yum: name={{ item }} state=present
  with_items:
    - git
    - libselinux-python
    - openssh-server
    - postfix
    - curl
    - openssl
    - python-pip

- name: Download GitLab repository installation script.
  get_url:
    url: "{{ gitlab_repository_installation_script_url }}"
    dest: /tmp/gitlab_install_repository.sh
    validate_certs: "{{ gitlab_download_validate_certs }}"
  when: (gitlab_file.stat.exists == false)

#- name:  GEt GitLAb repo installation script.
#  command: curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash

- name: Install GitLab repository
  command: bash /tmp/gitlab_install_repository.sh
  when: (gitlab_file.stat.exists == false)

- name: Install GitLab
  yum: name=gitlab-ce-9.1.4-ce.0.el6.x86_64  state=present
  when: (gitlab_file.stat.exists == false)

- name: Reconfigure GitLab (first run).
  command: >
    gitlab-ctl reconfigure
    creates=/var/opt/gitlab/bootstrapped
  when: (gitlab_file.stat.exists == false)
  failed_when: false

- name: Copy GitLab configuration file.
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0600

- name: Reconfigure GitLab.
  shell: gitlab-ctl reconfigure && gitlab-ctl start

- name: Install argparse
  easy_install:
    name: argparse
    state: latest

- name: Install python modules.
  shell: pip install {{ item }}
  with_items:
     - yamllint
     - pexpect

- name: Copy Gitlab backup archive.
  copy:
    src: 1496713308_2017_06_06_gitlab_backup.tar
    dest: /var/opt/gitlab/backups/
    owner: git
    group: git
    mode: 0600

- name: Stop Gitlab services.
  shell: gitlab-ctl stop unicorn && gitlab-ctl stop sidekiq

- name: Restore Gitlab from backup.
  expect: 
    command: gitlab-rake gitlab:backup:restore BACKUP=1496713308_2017_06_06
    responses:
      "Do you want to continue (yes/no)?": "yes"

- name: Stop iptables :).
  shell: service iptables stop

- name: Start Gitlab.
  shell: gitlab-ctl start
